# Generated by Django 5.1.3 on 2024-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_summary_user_alter_summary_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='notes_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
